[package]
name = "host"
version.workspace = true
edition.workspace = true
authors.workspace = true

# The host needs tonic for networking and tokio for running the compiler process asynchronously.
[dependencies]
common = { path = "../common" }
tonic = "0.12"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["net"] }
uuid = { version = "1.0", features = ["v4"] } # To give every job a unique folder
serde_json = "1.0"
dotenvy = "0.15.7"
clap = { version = "4.4", features = ["derive", "env"] }